import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  Ban,
  Bell,
  BookOpen,
  Box,
  Brain,
  Calculator,
  Calendar,
  ChartColumn,
  ChartColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleUser,
  CircleX,
  Clipboard,
  Clock,
  Cloud,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flame,
  FlaskConical,
  Gift,
  Globe,
  House,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Lightbulb,
  Link,
  ListFilter,
  Lock,
  LogIn,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Play,
  Plus,
  RefreshCcw,
  RefreshCw,
  Search,
  Server,
  Settings,
  Shield,
  Sparkles,
  SquarePen,
  Sun,
  Terminal,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap
} from 'lucide-vue-next'

/**
 * 图标名 → Lucide 组件映射。
 *
 * - 键名沿用历史命名（play / chevronDown / cog …），因此全站调用方无需改动。
 * - 类型即契约：`Icon` 组件的 name 属性是 `keyof typeof iconMap`，
 *   新增/改名会由 vue-tsc 直接报错，避免出现「图标静默丢失」。
 */
export const iconMap = {
  play: Play,
  refresh: RefreshCw,
  edit: SquarePen,
  trash: Trash2,
  plus: Plus,
  search: Search,
  more: Ellipsis,
  chart: ChartColumn,
  clock: Clock,
  link: Link,
  sync: RefreshCcw,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  check: Check,
  x: X,
  eye: Eye,
  eyeOff: EyeOff,
  cog: Settings,
  grid: LayoutGrid,
  chat: MessageCircle,
  lightbulb: Lightbulb,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowsUpDown: ArrowUpDown,
  chevronUp: ChevronUp,
  externalLink: ExternalLink,
  checkCircle: CircleCheck,
  xCircle: CircleX,
  exclamationCircle: CircleAlert,
  exclamationTriangle: TriangleAlert,
  trophy: Trophy,
  infoCircle: Info,
  questionCircle: CircleHelp,
  user: User,
  userCircle: CircleUser,
  userPlus: UserPlus,
  users: Users,
  document: FileText,
  clipboard: Clipboard,
  copy: Copy,
  inbox: Inbox,
  download: Download,
  upload: Upload,
  filter: ListFilter,
  globe: Globe,
  sort: ArrowUpDown,
  key: KeyRound,
  lock: Lock,
  shield: Shield,
  menu: Menu,
  calendar: Calendar,
  home: House,
  terminal: Terminal,
  gift: Gift,
  creditCard: CreditCard,
  mail: Mail,
  chartBar: ChartColumnIncreasing,
  trendingUp: TrendingUp,
  database: Database,
  cube: Box,
  bell: Bell,
  bolt: Zap,
  sparkles: Sparkles,
  cloud: Cloud,
  server: Server,
  sun: Sun,
  moon: Moon,
  book: BookOpen,
  dollar: DollarSign,
  ban: Ban,
  login: LogIn,
  swap: ArrowLeftRight,
  beaker: FlaskConical,
  cpu: Cpu,
  chatBubble: MessageSquare,
  calculator: Calculator,
  fire: Flame,
  badge: BadgeCheck,
  brain: Brain
} as const

export type IconName = keyof typeof iconMap

/** 未知图标名时的兜底图标（避免渲染出空节点） */
export const fallbackIcon = CircleHelp
